config:
  - monolith-slo: "monolith-slo.json"
  - docker-slo: "docker-slo.json"

monolith-slo:
  - name: "Monolith Error Rate"
  - mzname: "workshop/management-zone/mz-eztravel-monolith.name"

docker-slo:
  - name: "Docker Error Rate"
  - mzname: "workshop/management-zone/mz-eztravel-docker.name"
